const KEY='tiny-routines-v1';
const PENDING_KEY='tiny-routines-pending-v1';
const SUPABASE_URL='https://xmpghizpaxffjmwgfxih.supabase.co';
const SUPABASE_KEY='sb_publishable_FYBaxDTy_Dk34_FQHz4uMQ_WZ2KShqg';
const SHARED_ID='family';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{name:'little one',entries:[],activeTimer:null,nightMode:false,deletedEntries:{},profile:{},reminders:{enabled:false,intervalHours:3},feedingPlan:{enabled:true,dayOfLife:4,topUpMl:30},planSessions:[]};
state.activeTimer=state.activeTimer||null; state.nightMode=!!state.nightMode;
state.deletedEntries=state.deletedEntries||{};
state.profile=state.profile||{};state.reminders=state.reminders||{enabled:false,intervalHours:3};
state.feedingPlan=state.feedingPlan||{enabled:true,dayOfLife:4,topUpMl:30};state.planSessions=Array.isArray(state.planSessions)?state.planSessions:[];
let pendingChanges=JSON.parse(localStorage.getItem(PENDING_KEY)||'{}');
let supabaseClient=null, remoteReady=false, remoteBusy=false, loadBusy=false, syncQueued=false, lastSyncedAt=null;
let voiceRecognition=null, voiceRecording=false;
let editingEntryId=null;
let wakeLock=null;
const $=s=>document.querySelector(s);
const today=()=>new Date().toISOString().slice(0,10);
let selectedDate=today();
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function entryStamp(entry){return entry?.updatedAt||`${entry?.date||''}T${entry?.time||''}`}
function ensureEntryIds(entries){return (Array.isArray(entries)?entries:[]).map((entry,index)=>entry&&entry.id?entry:{...entry,id:`legacy-${entry?.date||'date'}-${entry?.time||'time'}-${entry?.type||'entry'}-${index}`})}
function pendingCount(){return Object.keys(pendingChanges).length}
function markPending(ids=['__state__']){ids.forEach(id=>{pendingChanges[id]=new Date().toISOString()});localStorage.setItem(PENDING_KEY,JSON.stringify(pendingChanges))}
function updateBadge(){let count=pendingCount();if('setAppBadge' in navigator){if(count)navigator.setAppBadge(count).catch(()=>{});else navigator.clearAppBadge?.().catch(()=>{})}}
function haptic(pattern=[8]){if(navigator.vibrate)navigator.vibrate(pattern);document.body.classList.remove('haptic-feedback');requestAnimationFrame(()=>{document.body.classList.add('haptic-feedback');setTimeout(()=>document.body.classList.remove('haptic-feedback'),180)})}
function setSyncStatus(kind,label){let node=$('#syncStatus');if(!node)return;let count=pendingCount();node.className='sync-status '+kind;node.textContent=count?`${label} · ${count} waiting`:label;node.title=lastSyncedAt?'Last synced '+new Date(lastSyncedAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}):label;updateBadge()}
function save(changedIds=['__state__']){haptic();markPending(changedIds);localStorage.setItem(KEY,JSON.stringify(state));render();if(!navigator.onLine){setSyncStatus('offline','Offline · saved here');return}if(remoteReady){syncQueued=true;setSyncStatus('syncing','Syncing…');syncRemote()}else setSyncStatus('offline','Waiting for sync')}
async function syncRemote(){if(!supabaseClient||!remoteReady)return;if(remoteBusy)return;remoteBusy=true;setSyncStatus('syncing','Syncing…');while(syncQueued){syncQueued=false;let payload=JSON.parse(JSON.stringify(state)),{error}=await supabaseClient.from('baby_shared_state').upsert({id:SHARED_ID,data:payload,updated_at:new Date().toISOString()});if(error){syncQueued=true;setSyncStatus('offline','Saved here · retrying');break}pendingChanges={};localStorage.setItem(PENDING_KEY,'{}');lastSyncedAt=Date.now()}remoteBusy=false;if(!syncQueued)setSyncStatus('synced','Synced')}
function mergeSharedState(remote){let remoteState=remote&&remote.data&&typeof remote.data==='object'?remote.data:remote;if(!remoteState||typeof remoteState!=='object')return false;let localEntries=ensureEntryIds(state.entries),remoteEntries=ensureEntryIds(remoteState.entries),localDeleted=state.deletedEntries||{},remoteDeleted=remoteState.deletedEntries||{},deleted={...remoteDeleted},needsPush=false;Object.entries(localDeleted).forEach(([id,stamp])=>{if(!deleted[id]||stamp>deleted[id]){deleted[id]=stamp;needsPush=true}});let byId=new Map();remoteEntries.forEach(entry=>{if(entry&&entry.id)byId.set(entry.id,entry)});localEntries.forEach(entry=>{if(!entry||!entry.id)return;let remoteEntry=byId.get(entry.id);if(!remoteEntry){byId.set(entry.id,entry);needsPush=true}else if(entryStamp(entry)>=entryStamp(remoteEntry)){byId.set(entry.id,entry);if(JSON.stringify(entry)!==JSON.stringify(remoteEntry))needsPush=true}});let entries=Array.from(byId.values()).filter(entry=>!deleted[entry.id]||deleted[entry.id]<entryStamp(entry)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));let mergedState={...state,...remoteState};if(pendingChanges.__profile__){mergedState.profile=state.profile;mergedState.name=state.name;needsPush=true}if(pendingChanges.__state__){mergedState.name=state.name;mergedState.nightMode=state.nightMode;mergedState.activeTimer=state.activeTimer;needsPush=true}if(pendingChanges.__plan__){mergedState.feedingPlan=state.feedingPlan;mergedState.planSessions=state.planSessions;needsPush=true}state={...mergedState,entries,deletedEntries:deleted};state.activeTimer=remoteState.activeTimer||state.activeTimer||null;state.nightMode=typeof remoteState.nightMode==='boolean'?remoteState.nightMode:!!state.nightMode;state.feedingPlan=state.feedingPlan||{enabled:true,dayOfLife:4,topUpMl:30};state.planSessions=Array.isArray(state.planSessions)?state.planSessions:[];return needsPush}
async function loadSharedState(){if(!supabaseClient||loadBusy)return;loadBusy=true;if(!navigator.onLine){setSyncStatus('offline','Offline · saved here');loadBusy=false;return}setSyncStatus('syncing','Checking sync…');let {data,error}=await supabaseClient.from('baby_shared_state').select('data').eq('id',SHARED_ID).maybeSingle();if(error){remoteReady=false;loadBusy=false;setSyncStatus('offline','Shared sync unavailable');return}remoteReady=true;let needsPush=data&&data.data?mergeSharedState(data.data):true;localStorage.setItem(KEY,JSON.stringify(state));if(needsPush){syncQueued=true;await syncRemote()}else{pendingChanges={};localStorage.setItem(PENDING_KEY,'{}');lastSyncedAt=Date.now();setSyncStatus('synced','Synced')}render();scheduleReminder();loadBusy=false}
function normaliseAnswer(value){return value.replace(/\D/g,'')}
function parseSpokenNumber(value){let clean=String(value).toLowerCase().replace(',','.');if(/^\d+(?:\.\d+)?$/.test(clean))return clean;let words={a:'1',an:'1',one:'1',two:'2',three:'3',four:'4',five:'5',six:'6',seven:'7',eight:'8',nine:'9',ten:'10',eleven:'11',twelve:'12',fifteen:'15',twenty:'20',thirty:'30',forty:'40',fortyfive:'45',sixty:'60',ninety:'90',hundred:'100'};let compact=clean.replace(/[ -]/g,'');return words[clean]||words[compact]||''}
function applyVoiceTranscript(transcript){let spoken=transcript.trim(),lower=spoken.toLowerCase(),type=$('#entryType').value,numeric='(?:\\d+(?:[.,]\\d+)?|a|an|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|fifteen|twenty|thirty|forty|forty five|fortyfive|sixty|ninety)',amount=lower.match(new RegExp('('+numeric+')\\s*(ounces?|ounce|oz|millilit(?:er|re)s?|ml)\\b')),duration=lower.match(new RegExp('('+numeric+')\\s*(minutes?|mins?|hours?|hrs?)\\b')),method=lower.match(/\\b(breast|breastfeed(?:ing)?|breastfed|nursing|pumped?|pumping|bottle|formula|syringe|cup)\\b/),side=lower.match(/\\b(left|right|both)\\b/),kind=lower.match(/\\b(wet|dirty|both|wet and dirty)\\b/),temperature=lower.match(/(\\d+(?:[.,]\\d+)?)\\s*(degrees?|°)?\\s*(celsius|centigrade|fahrenheit|c|f)\\b/),filled=false;if(type==='feed'){if(method){let value=method[1];$('#fieldMethod').value=value.startsWith('breast')||value==='nursing'?'Breast':/^pump/.test(value)?'Pumping':value[0].toUpperCase()+value.slice(1);filled=true}if(amount){$('#fieldAmount').value=parseSpokenNumber(amount[1]);$('#fieldAmountUnit').value=/ml|millilit/i.test(amount[2])?'ml':'oz';filled=true}if(duration&&$('#fieldDuration')){$('#fieldDuration').value=/hour|hr/i.test(duration[2])?Math.round(Number(parseSpokenNumber(duration[1]))*60):parseSpokenNumber(duration[1]);filled=true}if(side&&$('#fieldSide')&&(method&&(/breast|nursing|pump/.test(method[1]))||lower.includes('breast'))){let value=side[1];$('#fieldSide').value=value==='both'?'Both':value[0].toUpperCase()+value.slice(1);filled=true}}else if(type==='sleep'&&duration){let value=Number(parseSpokenNumber(duration[1]));$('#fieldDuration').value=/hour|hr/i.test(duration[2])?Math.round(value*60):value;filled=true}else if(type==='diaper'&&kind){$('#fieldKind').value=kind[1].includes('and')||kind[1]==='both'?'both':kind[1];filled=true}else if(type==='medication'){let words=lower.match(/(?:gave|give|log|logged)?\\s*(?:baby\\s+)?(.+?)(?:\\s+(?:dose|dosage)\\s+(.+))?$/);if(words&&words[1]){$('#fieldMedication').value=words[1].trim();if(words[2]){$('#fieldDose').value=parseSpokenNumber(words[2].replace(/[^\\d.]/g,''));$('#fieldDoseUnit').value=words[2].match(/ml|mg|drops?/i)?.[0]||'ml'}filled=true}}else if(type==='temperature'&&temperature){$('#fieldTemperature').value=temperature[1].replace(',','.');$('#fieldTemperatureUnit').value=/f|fahrenheit/i.test(temperature[3])?'°F':'°C';filled=true}note.value+=(note.value.trim()?' ':'')+spoken;toast(filled?'Form filled from voice':'Voice note added')}
async function requestWakeLock(){if(!('wakeLock' in navigator)||!state.activeTimer)return;try{wakeLock=await navigator.wakeLock.request('screen');wakeLock.addEventListener('release',()=>{wakeLock=null})}catch{}}
async function releaseWakeLock(){if(wakeLock){try{await wakeLock.release()}catch{}wakeLock=null}}
function setupVoiceNote(){let button=$('#voiceNoteButton');if(!button)return;let SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition){button.title='Voice notes are not supported in this browser';button.onclick=()=>toast('Voice notes are not supported here');return}voiceRecognition=new SpeechRecognition();voiceRecognition.continuous=false;voiceRecognition.interimResults=false;voiceRecognition.lang='en-GB';voiceRecognition.onstart=()=>{voiceRecording=true;button.classList.add('recording');button.textContent='■';button.title='Stop recording'};voiceRecognition.onresult=e=>{let transcript=Array.from(e.results).map(result=>result[0].transcript).join(' ');applyVoiceTranscript(transcript)};voiceRecognition.onerror=()=>toast('Microphone recording could not start');voiceRecognition.onend=()=>{voiceRecording=false;button.classList.remove('recording');button.textContent='●';button.title='Fill form from microphone'};button.onclick=()=>{if(voiceRecording)voiceRecognition.stop();else{try{voiceRecognition.start()}catch{toast('Microphone is already active')}}}}
async function startApp(){let answer=normaliseAnswer($('#accessAnswer').value);if(!['19092026','22092026'].includes(answer)){$('#authError').hidden=false;return}sessionStorage.setItem('tiny-routines-access','yes');$('#authGate').hidden=true;$('#app').hidden=false;await loadSharedState();render()}
function formatDate(date=today()){let d=new Date(date+'T12:00:00');return new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric'}).format(d)}
function shiftDate(amount){let d=new Date(selectedDate+'T12:00:00');d.setDate(d.getDate()+amount);selectedDate=d.toISOString().slice(0,10);render()}
function formatTime(t){let [h,m]=t.split(':');let d=new Date();d.setHours(h,m);return d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function elapsedMs(timer){if(!timer)return 0;let carried=Number(timer.elapsedBeforePause)||0;if(timer.pausedAt)return carried;return carried+Math.max(0,Date.now()-Number(timer.startedAt||Date.now()))}
function elapsedMinutes(start){return Math.max(0,Math.round((Date.now()-start)/60000))}
function elapsedLabel(timer){let total=Math.floor(elapsedMs(timer)/1000),hours=Math.floor(total/3600),minutes=Math.floor(total%3600/60),seconds=total%60;return hours?`${hours}h ${String(minutes).padStart(2,'0')}m ${String(seconds).padStart(2,'0')}s`:`${minutes}m ${String(seconds).padStart(2,'0')}s`}
function lastEntry(type){return state.entries.filter(e=>e.type===type).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time))[0]}
function handoverLine(type,name){let e=lastEntry(type);return e?`<div><b>${name}</b><span>${formatDate(e.date)} · ${formatTime(e.time)} · ${esc(meta(e))}</span></div>`:`<div><b>${name}</b><span>Not logged yet</span></div>`}
function handoverText(){return ['Tiny Routines handover', 'Last feed: '+(lastEntry('feed')?formatDate(lastEntry('feed').date)+' '+formatTime(lastEntry('feed').time)+' · '+meta(lastEntry('feed')):'Not logged'), 'Last sleep: '+(lastEntry('sleep')?formatDate(lastEntry('sleep').date)+' '+formatTime(lastEntry('sleep').time)+' · '+meta(lastEntry('sleep')):'Not logged'), 'Last diaper: '+(lastEntry('diaper')?formatDate(lastEntry('diaper').date)+' '+formatTime(lastEntry('diaper').time)+' · '+meta(lastEntry('diaper')):'Not logged'), 'Last medication: '+(lastEntry('medication')?formatDate(lastEntry('medication').date)+' '+formatTime(lastEntry('medication').time)+' · '+meta(lastEntry('medication')):'Not logged'), 'Last temperature: '+(lastEntry('temperature')?formatDate(lastEntry('temperature').date)+' '+formatTime(lastEntry('temperature').time)+' · '+meta(lastEntry('temperature')):'Not logged')].join('\\n')}
function shareHandover(){let text=handoverText();if(navigator.share){navigator.share({title:'Tiny Routines handover',text}).catch(()=>{})}else navigator.clipboard?.writeText(text).then(()=>toast('Handover copied'))}
function editBabyProfile(){let profile=state.profile||{},name=prompt('Baby name',profile.name||state.name||'little one');if(name===null)return;let dob=prompt('Date of birth (DD/MM/YYYY)',profile.dob||'');if(dob===null)return;let weight=prompt('Current weight (optional)',profile.weight||'');if(weight===null)return;let notes=prompt('Care notes (optional)',profile.notes||'');if(notes===null)return;state.profile={name:name.trim()||'little one',dob:dob.trim(),weight:weight.trim(),notes:notes.trim()};state.name=state.profile.name;save(['__profile__']);toast('Baby profile saved')}
function enableReminders(){if(!('Notification' in window)){toast('Notifications are not supported here');return}Notification.requestPermission().then(permission=>{if(permission!=='granted'){toast('Notifications remain off');return}let value=prompt('Remind us after how many hours without a feed?',String(state.reminders?.intervalHours||3));let hours=Number(value);if(!Number.isFinite(hours)||hours<=0)return;state.reminders={enabled:true,intervalHours:hours};save(['__reminders__']);scheduleReminder();toast('Feed reminders enabled')})}
function scheduleReminder(){if(!state.reminders?.enabled||!('Notification' in window)||Notification.permission!=='granted')return;let feed=lastEntry('feed'),interval=(Number(state.reminders.intervalHours)||3)*3600000,next=feed?new Date(`${feed.date}T${feed.time}`).getTime()+interval:Date.now()+interval;window.clearTimeout(window.tinyReminder);window.tinyReminder=window.setTimeout(()=>{if(!document.hidden)new Notification('Tiny Routines',{body:'It has been a while since the last feed was logged.'});scheduleReminder()},Math.max(1000,next-Date.now()))}
function bindTimerButton(){let b=$('#startTimer');if(b)b.onclick=()=>{let type=$('#entryType').value;if(type==='note'||type==='diaper')return;if(state.activeTimer){toast('Finish the current timer first');return}state.activeTimer={type,startedAt:Date.now(),elapsedBeforePause:0,pausedAt:null,date:selectedDate,time:$('#entryTime').value,method:type==='feed'?$('#fieldMethod').value:null};requestWakeLock();save();closeModal();toast((type==='feed'?'Feed':'Sleep')+' timer started')}}
function pauseTimer(){let t=state.activeTimer;if(!t||t.pausedAt)return;t.elapsedBeforePause=elapsedMs(t);t.pausedAt=Date.now();releaseWakeLock();save();toast('Timer paused')}
function resumeTimer(){let t=state.activeTimer;if(!t||!t.pausedAt)return;t.startedAt=Date.now();t.pausedAt=null;requestWakeLock();save();toast('Timer resumed')}
function cancelTimer(){if(!state.activeTimer)return;if(!confirm('Discard this timer without saving?'))return;state.activeTimer=null;releaseWakeLock();save();toast('Timer discarded')}
function stopTimer(){if(!state.activeTimer)return;let t=state.activeTimer,minutes=Math.max(1,Math.round(elapsedMs(t)/60000)),x={id:crypto.randomUUID(),date:t.date,time:t.time,type:t.type,duration:minutes,note:'Timed session',updatedAt:new Date().toISOString()};if(t.type==='feed')x.method=t.method||'Breast';state.entries.push(x);state.activeTimer=null;releaseWakeLock();save([x.id]);toast('Timer saved · '+minutes+' min')}
function mergeFeed(id){let source=state.entries.find(e=>e.id===id),others=state.entries.filter(e=>e.type==='feed'&&e.id!==id&&e.date===source?.date).sort((a,b)=>(a.time||'').localeCompare(b.time||''));if(!source||!others.length)return;let choices=others.map((e,i)=>`${i+1}. ${formatTime(e.time)} · ${meta(e)}`).join('\n'),choice=Number(prompt('Merge this feed with:\n'+choices+'\n\nEnter a number'))-1,other=others[choice];if(!other)return;let ordered=[source,other].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)),keep=ordered[0],remove=ordered[1],hasSourceAmount=source.amount!==undefined&&source.amount!=='',hasOtherAmount=other.amount!==undefined&&other.amount!=='',sameUnit=hasSourceAmount&&hasOtherAmount&&(source.amountUnit||'oz')===(other.amountUnit||'oz'),sameMethod=source.method===other.method,merged={...keep,updatedAt:new Date().toISOString(),duration:(Number(source.duration)||0)+(Number(other.duration)||0),note:[source.note,other.note].filter(Boolean).join(' · ')};if(sameMethod)merged.method=source.method;else merged.method='Mixed';if(sameUnit){merged.amount=Number(source.amount)+Number(other.amount);merged.amountUnit=source.amountUnit||'oz'}else if(hasSourceAmount&&!hasOtherAmount){merged.amount=source.amount;merged.amountUnit=source.amountUnit||'oz'}else if(!hasSourceAmount&&hasOtherAmount){merged.amount=other.amount;merged.amountUnit=other.amountUnit||'oz'}else{delete merged.amount;delete merged.amountUnit}if(['Breast','Pumping'].includes(source.method)&&['Breast','Pumping'].includes(other.method)){merged.side=source.side===other.side?source.side:'Both'}else delete merged.side;if(!merged.duration)delete merged.duration;state.deletedEntries[remove.id]=new Date().toISOString();state.entries=state.entries.filter(e=>e.id!==remove.id).map(e=>e.id===keep.id?merged:e);save([keep.id,remove.id]);toast('Feeds merged')}
function planDayOfLife(){let dob=state.profile?.dob?.match?.(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2,4})$/);if(dob){let year=Number(dob[3]);if(year<100)year+=2000;let birth=new Date(year,Number(dob[2])-1,Number(dob[1]),12),day=new Date(selectedDate+'T12:00:00');if(!Number.isNaN(birth.getTime()))return Math.max(1,Math.floor((day-birth)/86400000)+1)}return Number(state.feedingPlan?.dayOfLife)||4}
function planTarget(day){return day<=4?4:day===5?5:5}
function planEntriesForDate(){return state.planSessions.filter(e=>e.date===selectedDate).sort((a,b)=>(a.time||'').localeCompare(b.time||''))}
function renderFeedingPlan(){let card=$('#feedingPlanContent');if(!card)return;let day=planDayOfLife(),sessions=planEntriesForDate(),entries=state.entries.filter(e=>e.date===selectedDate),wet=entries.filter(e=>e.type==='diaper'&&(e.kind==='wet'||e.kind==='both')).length,dirty=entries.filter(e=>e.type==='diaper'&&(e.kind==='dirty'||e.kind==='both')).length,last=sessions[sessions.length-1],topup=last?Number(last.breastMilkMl||0)+Number(last.formulaMl||0):0;card.innerHTML=`<div class="plan-heading"><div><p class="eyebrow">FEEDING PLAN</p><h2>Top-up phase</h2></div><span class="plan-day">DAY ${day}</span></div><p class="subtle plan-summary">Breast first, offer up to ${Number(state.feedingPlan?.topUpMl)||30} ml total, then pump if you can.</p><div class="plan-progress"><div><strong>${sessions.length}</strong><span>feed cycles</span></div><div><strong>${wet}/${planTarget(day)}</strong><span>wet nappies</span></div><div><strong>${dirty}</strong><span>dirty nappies</span></div>${last?`<div><strong>${topup} ml</strong><span>last top-up</span></div>`:''}</div><div class="plan-actions"><button class="primary-button" id="startPlanFeed">Log planned feed</button><span class="plan-hint">Target: 30 ml total top-up</span></div>`;$('#startPlanFeed').onclick=openPlanModal}
function openPlanModal(){let last=planEntriesForDate().at(-1);$('#planTime').value=new Date().toTimeString().slice(0,5);$('#planStartSide').value=last?.startSide==='Left'?'Right':'Left';['planSideOneMinutes','planSideTwoMinutes','planBreastMilk','planFormula','planPumped'].forEach(id=>{$('#'+id).value=''});$('#planWet').checked=false;$('#planDirty').checked=false;$('#planNote').value='';updatePlanTopup();$('#planModalBackdrop').hidden=false;$('#planModalBackdrop').style.display='grid';$('#planStartSide').focus()}
function closePlanModal(){$('#planModalBackdrop').hidden=true;$('#planModalBackdrop').style.display='none'}
function updatePlanTopup(){let total=Number($('#planBreastMilk')?.value||0)+Number($('#planFormula')?.value||0),target=Number(state.feedingPlan?.topUpMl)||30,status=$('#planTopupStatus');if(!status)return;status.textContent=`${total} / ${target} ml top-up recorded`;status.className='plan-topup-status '+(total===target?'complete':total>target?'over':'')}
function savePlanSession(event){event.preventDefault();let now=new Date().toISOString(),session={id:crypto.randomUUID(),date:selectedDate,time:$('#planTime').value,startSide:$('#planStartSide').value,sideOneMinutes:$('#planSideOneMinutes').value,sideTwoMinutes:$('#planSideTwoMinutes').value,breastMilkMl:$('#planBreastMilk').value,formulaMl:$('#planFormula').value,pumpedMl:$('#planPumped').value,wet:$('#planWet').checked,dirty:$('#planDirty').checked,note:$('#planNote').value.trim(),updatedAt:now};state.planSessions.push(session);let ids=[session.id];if(session.wet||session.dirty){let diaper={id:crypto.randomUUID(),date:selectedDate,time:session.time,type:'diaper',kind:session.wet&&session.dirty?'both':session.wet?'wet':'dirty',note:'Logged with feeding plan',updatedAt:now};state.entries.push(diaper);ids.push(diaper.id)}save(['__plan__',...ids]);closePlanModal();toast('Feed cycle saved')}
function render(){
 document.body.classList.toggle('night-mode',state.nightMode); $('#nightModeButton').textContent=state.nightMode?'☀':'☾';
 $('#displayName').textContent=state.name; $('#babyNameButton').textContent=(state.name[0]||'L').toUpperCase(); $('#todayLabel').textContent=formatDate(selectedDate)+(selectedDate===today()?'':' · history');
 $('#clearToday').textContent=selectedDate===today()?'Clear today':'Clear this day';
 const entries=state.entries.filter(e=>e.date===selectedDate).sort((a,b)=>a.time.localeCompare(b.time));
 const feeds=entries.filter(e=>e.type==='feed'), diapers=entries.filter(e=>e.type==='diaper'), sleeps=entries.filter(e=>e.type==='sleep');
 $('#feedsCount').textContent=feeds.length; $('#diaperCount').textContent=diapers.length; $('#wetCount').textContent=diapers.filter(e=>e.kind==='wet'||e.kind==='both').length+' wet'; $('#dirtyCount').textContent=diapers.filter(e=>e.kind==='dirty'||e.kind==='both').length+' dirty'; let lastFeed=feeds.slice().sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time))[0],breastFeeds=feeds.filter(e=>e.method==='Breast'),leftFeeds=breastFeeds.filter(e=>e.side==='Left').length,rightFeeds=breastFeeds.filter(e=>e.side==='Right').length,bothFeeds=breastFeeds.filter(e=>e.side==='Both').length; $('#lastFeedTime').textContent=lastFeed?formatTime(lastFeed.time):'—'; $('#lastFeedDetail').textContent=lastFeed?meta(lastFeed):'No feed yet'; $('#breastSideCount').textContent=breastFeeds.length; $('#leftFeedCount').textContent=leftFeeds+' left'; $('#rightFeedCount').textContent=rightFeeds+' right'; $('#bothFeedCount').textContent=bothFeeds+' both';
 let mins=sleeps.reduce((n,e)=>n+(Number(e.duration)||0),0),pumped=feeds.filter(e=>e.method==='Pumping'),pumpedAmount=pumped.reduce((n,e)=>n+(Number(e.amount)||0),0); $('#sleepTotal').textContent=Math.floor(mins/60)+'h '+(mins%60)+'m'; $('#sleepBarFill').style.width=Math.min(100,mins/900*100)+'%'; $('#summaryDate').textContent=selectedDate===today()?'Today at a glance':formatDate(selectedDate); $('#summaryFeeds').textContent=feeds.length; $('#summarySleep').textContent=Math.floor(mins/60)+'h '+(mins%60)+'m'; $('#summaryDiapers').textContent=diapers.length; $('#summaryPumping').textContent=pumpedAmount?`${pumpedAmount} ${pumped[0]?.amountUnit||'oz'}`:pumped.length;
 renderFeedingPlan();
 let timer=$('#activeTimer');if(state.activeTimer){let t=state.activeTimer,paused=!!t.pausedAt;timer.hidden=false;timer.innerHTML=`<div class="timer-copy"><p class="eyebrow">${paused?'PAUSED':'IN PROGRESS'}</p><strong>${t.type==='feed'?'Feeding':'Sleep'}</strong><span class="timer-elapsed">${elapsedLabel(t)}</span><small>${paused?'Timer paused':'Keep this screen open or lock it safely'}</small></div><div class="timer-actions"><button class="secondary-button" id="pauseTimer">${paused?'Resume':'Pause'}</button><button class="primary-button" id="stopTimer">Finish & save</button><button class="text-button" id="cancelTimer">Discard</button></div>`;$('#pauseTimer').onclick=paused?resumeTimer:pauseTimer;$('#stopTimer').onclick=stopTimer;$('#cancelTimer').onclick=cancelTimer}else{timer.hidden=true;timer.innerHTML=''}
 $('#handoverSummary').innerHTML=handoverLine('feed','Last feed')+handoverLine('sleep','Last sleep')+handoverLine('diaper','Last diaper');
 let days=[];for(let i=6;i>=0;i--){let d=new Date(selectedDate+'T12:00:00');d.setDate(d.getDate()-i);let key=d.toISOString().slice(0,10),day=state.entries.filter(e=>e.date===key);days.push({label:d.toLocaleDateString(undefined,{weekday:'short'}).slice(0,2),feeds:day.filter(e=>e.type==='feed').length,sleep:day.filter(e=>e.type==='sleep').reduce((n,e)=>n+(Number(e.duration)||0),0),diapers:day.filter(e=>e.type==='diaper').length,pumping:day.filter(e=>e.type==='feed'&&e.method==='Pumping').reduce((n,e)=>n+(Number(e.amount)||0),0)})};let max=Math.max(1,...days.map(d=>d.feeds));$('#patterns').innerHTML=days.map(d=>`<div class="pattern-day"><span>${d.label}</span><i style="height:${Math.max(8,d.feeds/max*42)}px" title="${d.feeds} feeds"></i><small>${d.feeds}</small></div>`).join('');let weekFeeds=days.reduce((n,d)=>n+d.feeds,0),weekSleep=days.reduce((n,d)=>n+d.sleep,0),weekDiapers=days.reduce((n,d)=>n+d.diapers,0),weekPumping=days.reduce((n,d)=>n+d.pumping,0);$('#trendSummary').innerHTML=`<span>${(weekFeeds/7).toFixed(1)} feeds/day</span><span>${Math.round(weekSleep/7)} min sleep/day</span><span>${(weekDiapers/7).toFixed(1)} diapers/day</span>${weekPumping?`<span>${weekPumping} pumped units</span>`:''}`;
 const timeline=$('#timeline'); timeline.classList.toggle('empty-state',!entries.length);
 timeline.innerHTML=entries.length?entries.map(e=>`<div class="timeline-entry"><div class="entry-time">${formatTime(e.time)}</div><div class="entry-rail"><i class="entry-dot"></i></div><div class="entry-body"><div class="entry-actions"><button class="edit-entry" data-edit="${e.id}">Edit</button>${e.type==='feed'&&feeds.length>1?`<button class="merge-entry" data-merge="${e.id}">Merge</button>`:''}<button class="duplicate-entry" data-duplicate="${e.id}">Duplicate</button><button class="delete-entry" data-delete="${e.id}" aria-label="Delete entry">×</button></div><div class="entry-title">${esc(label(e))}</div><div class="entry-meta">${esc(meta(e))}${e.note?' · '+esc(e.note):''}</div></div></div>`).join(''):`<div class="empty-illustration">☼</div><h3>A quiet start</h3><p>Log a feed, nap, diaper, or note to begin today's rhythm.</p>`;
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{let entry=state.entries.find(e=>e.id===b.dataset.edit);if(entry)openModal(entry.type,entry)});
 document.querySelectorAll('[data-duplicate]').forEach(b=>b.onclick=()=>{let entry=state.entries.find(e=>e.id===b.dataset.duplicate);if(entry)openModal(entry.type,entry,true)});
 document.querySelectorAll('[data-merge]').forEach(b=>b.onclick=()=>mergeFeed(b.dataset.merge));
 document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{let id=b.dataset.delete;state.deletedEntries[id]=new Date().toISOString();state.entries=state.entries.filter(e=>e.id!==id);save([id]);toast('Entry removed')});
}
function label(e){return e.type==='feed'?'Feed':e.type==='sleep'?'Sleep':e.type==='diaper'?'Diaper':e.type==='medication'?'Medication':e.type==='temperature'?'Temperature':'Note'}
function meta(e){if(e.type==='feed')return `${e.method||'Feed'}${(e.method==='Breast'||e.method==='Pumping')&&e.side?' · '+e.side:''}${e.amount?' · '+e.amount+' '+(e.amountUnit||'oz'):''}${e.duration?' · '+e.duration+' min':''}`;if(e.type==='sleep')return `${e.duration||0} minutes`;if(e.type==='diaper')return (e.kind||'wet').replace(/^./,x=>x.toUpperCase());if(e.type==='medication')return `${e.medication||'Medication'}${e.dose?' · '+e.dose+' '+(e.doseUnit||''):''}`;if(e.type==='temperature')return `${e.temperature||'—'} ${e.temperatureUnit||'°C'}`;return 'Remembered moment'}
function fields(type,entry=null){if(type==='feed'){return '<label>Method<select id="fieldMethod"><option>Breast</option><option>Pumping</option><option>Bottle</option><option>Formula</option><option>Syringe</option><option>Cup</option></select></label><label id="breastSideField">Side<select id="fieldSide"><option>Left</option><option>Right</option><option>Both</option></select></label><label>Amount (optional)<div class="amount-row"><input id="fieldAmount" type="number" min="0" step="0.5" placeholder="Amount"><select id="fieldAmountUnit" aria-label="Amount unit"><option value="oz">oz</option><option value="ml">ml</option></select></div></label><label>Duration (optional, minutes)<input id="fieldDuration" type="number" min="1" placeholder="e.g. 20"></label><button type="button" id="startTimer" class="timer-button">Start feed timer</button>'}if(type==='sleep')return '<label>Duration (minutes)<input id="fieldDuration" type="number" min="1" placeholder="e.g. 45"></label><button type="button" id="startTimer" class="timer-button">Start sleep timer</button>';if(type==='diaper')return '<label>Type<select id="fieldKind"><option value="wet">Wet</option><option value="dirty">Dirty</option><option value="both">Wet + dirty</option></select></label>';if(type==='medication')return '<label>Medication<input id="fieldMedication" type="text" placeholder="e.g. vitamin D"></label><label>Dose (optional)<div class="amount-row"><input id="fieldDose" type="number" min="0" step="0.1" placeholder="Dose"><input id="fieldDoseUnit" type="text" placeholder="ml"></div></label>';if(type==='temperature')return '<label>Temperature<input id="fieldTemperature" type="number" min="30" max="45" step="0.1" placeholder="e.g. 37.2"></label><label>Unit<select id="fieldTemperatureUnit"><option value="°C">°C</option><option value="°F">°F</option></select></label>';return '<p class="subtle" style="margin-top:14px">Capture a sweet moment, a question, or anything you want to remember.</p>'}
const baseFields=fields;fields=function(type,entry=null){let html=baseFields(type,entry);return type==='feed'?html.replace('<option>Cup</option>','<option>Cup</option><option>Mixed</option>'):html}
function bindFeedMethod(){let method=$('#fieldMethod'),side=$('#breastSideField');if(!method||!side)return;let update=()=>{side.hidden=!['Breast','Pumping'].includes(method.value)};method.onchange=update;update()}
 function syncLogTypeTabs(){let type=$('#entryType')?.value;document.querySelectorAll('[data-log-type]').forEach(button=>button.classList.toggle('active',button.dataset.logType===type||button.dataset.logType==='medication'&&['medication','temperature'].includes(type)))}
 function openModal(type='feed',entry=null,duplicate=false){ editingEntryId=duplicate?null:entry?.id||null; $('#entryType').value=type; $('#dynamicFields').innerHTML=fields(type,entry); $('#entryTime').value=duplicate?new Date().toTimeString().slice(0,5):entry?.time||new Date().toTimeString().slice(0,5); $('#entryNote').value=entry?.note||''; $('#modalTitle').textContent=entry&&!duplicate?'Edit activity':'Log something'; $('#entryForm button[type="submit"]').textContent=entry&&!duplicate?'Save changes':'Save entry'; if(entry&&type==='feed'){ $('#fieldMethod').value=entry.method||'Breast'; $('#fieldSide').value=entry.side||'Both'; $('#fieldAmount').value=entry.amount||''; $('#fieldAmountUnit').value=entry.amountUnit||'oz'; if($('#fieldDuration'))$('#fieldDuration').value=entry.duration||'' }else if(entry&&type==='sleep')$('#fieldDuration').value=entry.duration||'';else if(entry&&type==='diaper')$('#fieldKind').value=entry.kind||'wet';else if(entry&&type==='medication'){ $('#fieldMedication').value=entry.medication||'';$('#fieldDose').value=entry.dose||'';$('#fieldDoseUnit').value=entry.doseUnit||'ml' }else if(entry&&type==='temperature'){ $('#fieldTemperature').value=entry.temperature||'';$('#fieldTemperatureUnit').value=entry.temperatureUnit||'°C' }syncLogTypeTabs();bindFeedMethod(); $('#modalBackdrop').hidden=false; $('#modalBackdrop').style.display='grid'; bindTimerButton(); $('#entryType').focus() }
 function closeModal(){ if(voiceRecording&&voiceRecognition)voiceRecognition.stop(); editingEntryId=null; $('#modalBackdrop').hidden=true; $('#modalBackdrop').style.display='none' }
 $('#addEntryButton').onclick=()=>openModal(); document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{openModal(b.dataset.quick);if(b.dataset.method){$('#fieldMethod').value=b.dataset.method;bindFeedMethod()}}); document.querySelectorAll('[data-log-type]').forEach(b=>b.onclick=()=>{$('#entryType').value=b.dataset.logType;$('#dynamicFields').innerHTML=fields(b.dataset.logType);syncLogTypeTabs();bindFeedMethod();bindTimerButton()}); $('#closeModal').onclick=e=>{e.preventDefault();closeModal()}; $('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()}; document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modalBackdrop').hidden)closeModal()}); $('#entryType').onchange=e=>{$('#dynamicFields').innerHTML=fields(e.target.value);syncLogTypeTabs();bindFeedMethod();bindTimerButton()};
 $('#closePlanModal').onclick=e=>{e.preventDefault();closePlanModal()}; $('#planModalBackdrop').onclick=e=>{if(e.target.id==='planModalBackdrop')closePlanModal()}; $('#planForm').onsubmit=savePlanSession; ['planBreastMilk','planFormula'].forEach(id=>$('#'+id).oninput=updatePlanTopup);
 setupVoiceNote();
 $('#entryForm').onsubmit=e=>{e.preventDefault();let type=$('#entryType').value,existing=editingEntryId?state.entries.find(entry=>entry.id===editingEntryId):null,x=existing?{...existing}:{id:crypto.randomUUID()};x.date=selectedDate;x.time=$('#entryTime').value;x.type=type;x.note=$('#entryNote').value.trim();x.updatedAt=new Date().toISOString();if(type==='feed'){x.method=$('#fieldMethod').value;x.amount=$('#fieldAmount').value;x.amountUnit=$('#fieldAmountUnit').value;if(x.method==='Breast'||x.method==='Pumping')x.side=$('#fieldSide').value;else delete x.side;if($('#fieldDuration'))x.duration=$('#fieldDuration').value}else if(type==='sleep')x.duration=$('#fieldDuration').value;else if(type==='diaper')x.kind=$('#fieldKind').value;else if(type==='medication'){x.medication=$('#fieldMedication').value.trim();x.dose=$('#fieldDose').value;x.doseUnit=$('#fieldDoseUnit').value.trim()}else if(type==='temperature'){x.temperature=$('#fieldTemperature').value;x.temperatureUnit=$('#fieldTemperatureUnit').value}delete state.deletedEntries[x.id];if(existing)state.entries=state.entries.map(entry=>entry.id===editingEntryId?x:entry);else state.entries.push(x);save([x.id]);scheduleReminder();closeModal();toast(existing?'Activity updated':'Saved to '+(selectedDate===today()?'today':'history'));e.target.reset();$('#modalTitle').textContent='Log something';$('#entryForm button[type="submit"]').textContent='Save entry'};
 $('#clearToday').onclick=()=>{if(confirm('Clear all entries for '+formatDate(selectedDate)+'?')){let removed=state.entries.filter(e=>e.date===selectedDate);removed.forEach(e=>state.deletedEntries[e.id]=new Date().toISOString());state.entries=state.entries.filter(e=>e.date!==selectedDate);save(removed.map(e=>e.id));toast('Day cleared')}};
 $('#babyNameButton').onclick=()=>{let n=prompt('What should we call your baby?',state.name);if(n&&n.trim()){state.name=n.trim();save()}};
 const exportData=()=>download('tiny-routines.json',JSON.stringify(state,null,2),'application/json'); const exportCsv=()=>{let rows=[['Date','Time','Type','Details','Note'],...state.entries.slice().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(e=>[e.date,e.time,label(e),meta(e),e.note||''])];download('tiny-routines.csv',rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\\n'),'text/csv')}; $('#exportTop').onclick=exportData; $('#downloadJson').onclick=exportData; $('#downloadCsv').onclick=exportCsv; $('#copyData').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(state,null,2));toast('Data copied to clipboard')}catch{toast('Copy unavailable in this browser')}}; $('#shareHandover').onclick=shareHandover; $('#copyHandover').onclick=async()=>{try{await navigator.clipboard.writeText(handoverText());toast('Handover copied')}catch{toast('Copy unavailable in this browser')}}; $('#babyProfile').onclick=editBabyProfile; $('#enableReminders').onclick=enableReminders; $('#printReport').onclick=()=>window.print(); $('#nightModeButton').onclick=()=>{state.nightMode=!state.nightMode;save()};
 $('#prevDay').onclick=()=>shiftDate(-1); $('#nextDay').onclick=()=>shiftDate(1); $('#jumpToday').onclick=()=>{selectedDate=today();render()}; $('#restoreData').onclick=()=>$('#restoreInput').click(); $('#restoreInput').onchange=e=>{let file=e.target.files[0];if(!file)return;let reader=new FileReader();reader.onload=()=>{try{let restored=JSON.parse(reader.result);if(!restored||!Array.isArray(restored.entries))throw new Error();state={name:restored.name||'little one',entries:restored.entries};save();toast('Backup restored')}catch{toast('That backup could not be read')}};reader.readAsText(file)};
 $('#mobileHome').onclick=()=>{selectedDate=today();render();window.scrollTo({top:0,behavior:'smooth'})}; $('#mobileHistory').onclick=()=>{selectedDate=new Date(Date.now()-86400000).toISOString().slice(0,10);render();window.scrollTo({top:0,behavior:'smooth'})}; $('#mobileAdd').onclick=()=>openModal(); $('#mobileExport').onclick=exportData;
 $('#accessForm').onsubmit=e=>{e.preventDefault();startApp()};
 $('#accessAnswer').oninput=e=>{let digits=e.target.value.replace(/\D/g,'').slice(0,8);let formatted=digits;if(digits.length>2)formatted=digits.slice(0,2)+' / '+digits.slice(2);if(digits.length>4)formatted=digits.slice(0,2)+' / '+digits.slice(2,4)+' / '+digits.slice(4);e.target.value=formatted};
 supabaseClient=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});if(sessionStorage.getItem('tiny-routines-access')==='yes'){$('#authGate').hidden=true;$('#app').hidden=false;loadSharedState()};window.addEventListener('online',()=>loadSharedState());window.addEventListener('offline',()=>setSyncStatus('offline','Offline · saved here'));document.addEventListener('visibilitychange',()=>{if(!document.hidden){loadSharedState();if(state.activeTimer)requestWakeLock()}});
function download(name,data,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href);toast('Download ready')}
function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
setInterval(()=>{if(state.activeTimer)render();if(!document.hidden&&remoteReady)loadSharedState()},30000);
