const KEY='tiny-routines-v1';
const SUPABASE_URL='https://xmpghizpaxffjmwgfxih.supabase.co';
const SUPABASE_KEY='sb_publishable_FYBaxDTy_Dk34_FQHz4uMQ_WZ2KShqg';
const SHARED_ID='family';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{name:'little one',entries:[],activeTimer:null,nightMode:false};
state.activeTimer=state.activeTimer||null; state.nightMode=!!state.nightMode;
let supabaseClient=null, remoteReady=false, remoteBusy=false;
let voiceRecognition=null, voiceRecording=false;
let editingEntryId=null;
const $=s=>document.querySelector(s);
const today=()=>new Date().toISOString().slice(0,10);
let selectedDate=today();
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(state));render();if(remoteReady&&!remoteBusy)syncRemote()}
async function syncRemote(){if(!supabaseClient)return;remoteBusy=true;let {error}=await supabaseClient.from('baby_shared_state').upsert({id:SHARED_ID,data:state,updated_at:new Date().toISOString()});remoteBusy=false;if(error)toast('Saved locally. Shared sync needs setup')}
function mergeSharedState(remote){let remoteState=remote&&remote.data&&typeof remote.data==='object'?remote.data:remote; if(!remoteState||typeof remoteState!=='object')return false;let localEntries=Array.isArray(state.entries)?state.entries:[],remoteEntries=Array.isArray(remoteState.entries)?remoteState.entries:[],byId=new Map();remoteEntries.forEach(entry=>{if(entry&&entry.id)byId.set(entry.id,entry)});localEntries.forEach(entry=>{if(entry&&entry.id&&!byId.has(entry.id))byId.set(entry.id,entry)});state={...state,...remoteState,entries:Array.from(byId.values()).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))};state.activeTimer=remoteState.activeTimer||state.activeTimer||null;state.nightMode=typeof remoteState.nightMode==='boolean'?remoteState.nightMode:!!state.nightMode;return localEntries.some(entry=>entry&&entry.id&&!remoteEntries.some(remoteEntry=>remoteEntry&&remoteEntry.id===entry.id))}
async function loadSharedState(){if(!supabaseClient)return;let {data,error}=await supabaseClient.from('baby_shared_state').select('data').eq('id',SHARED_ID).maybeSingle();if(error){toast('Shared storage needs setup');return}if(data&&data.data){let hadLocalOnlyEntries=mergeSharedState(data.data);localStorage.setItem(KEY,JSON.stringify(state));remoteReady=true;if(hadLocalOnlyEntries)await syncRemote()}else{remoteReady=true;await syncRemote()}render()}
function normaliseAnswer(value){return value.replace(/\D/g,'')}
function applyVoiceTranscript(transcript){let spoken=transcript.trim(),lower=spoken.toLowerCase(),type=$('#entryType').value,note=$('#entryNote'),amount=lower.match(/(\d+(?:[.,]\d+)?)\s*(ounces?|ounce|oz|millilit(?:er|re)s?|ml)\b/),duration=lower.match(/(\d+(?:[.,]\d+)?)\s*(minutes?|mins?|hours?|hrs?)\b/),method=lower.match(/\b(breast|breastfeed(?:ing)?|bottle|formula|syringe|cup)\b/),side=lower.match(/\b(left|right|both)\b/),kind=lower.match(/\b(wet|dirty|both|wet and dirty)\b/);if(type==='feed'){if(method){let value=method[1];$('#fieldMethod').value=value.startsWith('breast')?'Breast':value[0].toUpperCase()+value.slice(1)}if(amount){$('#fieldAmount').value=amount[1].replace(',','.');$('#fieldAmountUnit').value=/ml|millilit/i.test(amount[2])?'ml':'oz'}if(duration&&$('#fieldDuration'))$('#fieldDuration').value=/hour|hr/i.test(duration[2])?Math.round(Number(duration[1].replace(',','.'))*60):duration[1].replace(',','.');if(side&&$('#fieldSide')&&(method&&method[1].startsWith('breast')||lower.includes('breast'))){let value=side[1];$('#fieldSide').value=value==='both'?'Both':value[0].toUpperCase()+value.slice(1)}}else if(type==='sleep'&&duration){let value=Number(duration[1].replace(',','.'));$('#fieldDuration').value=/hour|hr/i.test(duration[2])?Math.round(value*60):value}else if(type==='diaper'&&kind){$('#fieldKind').value=kind[1].includes('and')||kind[1]==='both'?'both':kind[1]}note.value+=(note.value.trim()?' ':'')+spoken;toast(type==='feed'&&method||type==='sleep'&&duration||type==='diaper'&&kind?'Form filled from voice':'Voice note added')}
function setupVoiceNote(){let button=$('#voiceNoteButton');if(!button)return;let SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition){button.title='Voice notes are not supported in this browser';button.onclick=()=>toast('Voice notes are not supported here');return}voiceRecognition=new SpeechRecognition();voiceRecognition.continuous=false;voiceRecognition.interimResults=false;voiceRecognition.lang='en-GB';voiceRecognition.onstart=()=>{voiceRecording=true;button.classList.add('recording');button.textContent='■';button.title='Stop recording'};voiceRecognition.onresult=e=>{let transcript=Array.from(e.results).map(result=>result[0].transcript).join(' ');applyVoiceTranscript(transcript)};voiceRecognition.onerror=()=>toast('Microphone recording could not start');voiceRecognition.onend=()=>{voiceRecording=false;button.classList.remove('recording');button.textContent='●';button.title='Fill form from microphone'};button.onclick=()=>{if(voiceRecording)voiceRecognition.stop();else{try{voiceRecognition.start()}catch{toast('Microphone is already active')}}}}
async function startApp(){if(normaliseAnswer($('#accessAnswer').value)!=='19092026'){$('#authError').hidden=false;return}sessionStorage.setItem('tiny-routines-access','yes');$('#authGate').hidden=true;$('#app').hidden=false;await loadSharedState();render()}
function formatDate(date=today()){let d=new Date(date+'T12:00:00');return new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric'}).format(d)}
function shiftDate(amount){let d=new Date(selectedDate+'T12:00:00');d.setDate(d.getDate()+amount);selectedDate=d.toISOString().slice(0,10);render()}
function formatTime(t){let [h,m]=t.split(':');let d=new Date();d.setHours(h,m);return d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function elapsedMinutes(start){return Math.max(0,Math.round((Date.now()-start)/60000))}
function lastEntry(type){return state.entries.filter(e=>e.type===type).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time))[0]}
function handoverLine(type,name){let e=lastEntry(type);return e?`<div><b>${name}</b><span>${formatDate(e.date)} · ${formatTime(e.time)} · ${esc(meta(e))}</span></div>`:`<div><b>${name}</b><span>Not logged yet</span></div>`}
function handoverText(){return ['Last feed: '+(lastEntry('feed')?formatDate(lastEntry('feed').date)+' '+formatTime(lastEntry('feed').time)+' · '+meta(lastEntry('feed')):'Not logged'), 'Last sleep: '+(lastEntry('sleep')?formatDate(lastEntry('sleep').date)+' '+formatTime(lastEntry('sleep').time)+' · '+meta(lastEntry('sleep')):'Not logged'), 'Last diaper: '+(lastEntry('diaper')?formatDate(lastEntry('diaper').date)+' '+formatTime(lastEntry('diaper').time)+' · '+meta(lastEntry('diaper')):'Not logged')].join('\n')}
function bindTimerButton(){let b=$('#startTimer');if(b)b.onclick=()=>{let type=$('#entryType').value;if(type==='note'||type==='diaper')return;state.activeTimer={type,startedAt:Date.now(),date:selectedDate,time:$('#entryTime').value,method:type==='feed'?$('#fieldMethod').value:null};save();closeModal();toast((type==='feed'?'Feed':'Sleep')+' timer started')}}
function stopTimer(){if(!state.activeTimer)return;let t=state.activeTimer,minutes=Math.max(1,elapsedMinutes(t.startedAt));let x={id:crypto.randomUUID(),date:t.date,time:t.time,type:t.type,duration:minutes,note:'Timed session'};if(t.type==='feed')x.method=t.method||'Breast';state.entries.push(x);state.activeTimer=null;save();toast('Timer saved')}
function render(){
 document.body.classList.toggle('night-mode',state.nightMode); $('#nightModeButton').textContent=state.nightMode?'☀':'☾';
 $('#displayName').textContent=state.name; $('#babyNameButton').textContent=(state.name[0]||'L').toUpperCase(); $('#todayLabel').textContent=formatDate(selectedDate)+(selectedDate===today()?'':' · history');
 $('#clearToday').textContent=selectedDate===today()?'Clear today':'Clear this day';
 const entries=state.entries.filter(e=>e.date===selectedDate).sort((a,b)=>a.time.localeCompare(b.time));
 const feeds=entries.filter(e=>e.type==='feed'), diapers=entries.filter(e=>e.type==='diaper'), sleeps=entries.filter(e=>e.type==='sleep');
 $('#feedsCount').textContent=feeds.length; $('#diaperCount').textContent=diapers.length; $('#wetCount').textContent=diapers.filter(e=>e.kind==='wet'||e.kind==='both').length+' wet'; $('#dirtyCount').textContent=diapers.filter(e=>e.kind==='dirty'||e.kind==='both').length+' dirty'; let lastFeed=feeds.slice().sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time))[0],breastFeeds=feeds.filter(e=>e.method==='Breast'),leftFeeds=breastFeeds.filter(e=>e.side==='Left').length,rightFeeds=breastFeeds.filter(e=>e.side==='Right').length,bothFeeds=breastFeeds.filter(e=>e.side==='Both').length; $('#lastFeedTime').textContent=lastFeed?formatTime(lastFeed.time):'—'; $('#lastFeedDetail').textContent=lastFeed?meta(lastFeed):'No feed yet'; $('#breastSideCount').textContent=breastFeeds.length; $('#leftFeedCount').textContent=leftFeeds+' left'; $('#rightFeedCount').textContent=rightFeeds+' right'; $('#bothFeedCount').textContent=bothFeeds+' both';
 let mins=sleeps.reduce((n,e)=>n+(Number(e.duration)||0),0); $('#sleepTotal').textContent=Math.floor(mins/60)+'h '+(mins%60)+'m'; $('#sleepBarFill').style.width=Math.min(100,mins/900*100)+'%';
 let timer=$('#activeTimer');if(state.activeTimer){let t=state.activeTimer;timer.hidden=false;timer.innerHTML=`<div><p class="eyebrow">IN PROGRESS</p><strong>${t.type==='feed'?'Feeding':'Sleep'}</strong><span>${elapsedMinutes(t.startedAt)} min</span></div><button class="primary-button" id="stopTimer">Stop and save</button>`;$('#stopTimer').onclick=stopTimer}else{timer.hidden=true;timer.innerHTML=''}
 $('#handoverSummary').innerHTML=handoverLine('feed','Last feed')+handoverLine('sleep','Last sleep')+handoverLine('diaper','Last diaper');
 let days=[];for(let i=6;i>=0;i--){let d=new Date(selectedDate+'T12:00:00');d.setDate(d.getDate()-i);let key=d.toISOString().slice(0,10),day=state.entries.filter(e=>e.date===key);days.push({label:d.toLocaleDateString(undefined,{weekday:'short'}).slice(0,2),feeds:day.filter(e=>e.type==='feed').length,sleep:day.filter(e=>e.type==='sleep').reduce((n,e)=>n+(Number(e.duration)||0),0),diapers:day.filter(e=>e.type==='diaper').length})};let max=Math.max(1,...days.map(d=>d.feeds));$('#patterns').innerHTML=days.map(d=>`<div class="pattern-day"><span>${d.label}</span><i style="height:${Math.max(8,d.feeds/max*42)}px" title="${d.feeds} feeds"></i><small>${d.feeds}</small></div>`).join('');
 const timeline=$('#timeline'); timeline.classList.toggle('empty-state',!entries.length);
 timeline.innerHTML=entries.length?entries.map(e=>`<div class="timeline-entry"><div class="entry-time">${formatTime(e.time)}</div><div class="entry-rail"><i class="entry-dot"></i></div><div class="entry-body"><div class="entry-actions"><button class="edit-entry" data-edit="${e.id}">Edit</button><button class="duplicate-entry" data-duplicate="${e.id}">Duplicate</button><button class="delete-entry" data-delete="${e.id}" aria-label="Delete entry">×</button></div><div class="entry-title">${esc(label(e))}</div><div class="entry-meta">${esc(meta(e))}${e.note?' · '+esc(e.note):''}</div></div></div>`).join(''):`<div class="empty-illustration">☼</div><h3>A quiet start</h3><p>Log a feed, nap, diaper, or note to begin today's rhythm.</p>`;
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{let entry=state.entries.find(e=>e.id===b.dataset.edit);if(entry)openModal(entry.type,entry)});
 document.querySelectorAll('[data-duplicate]').forEach(b=>b.onclick=()=>{let entry=state.entries.find(e=>e.id===b.dataset.duplicate);if(entry)openModal(entry.type,entry,true)});
 document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{state.entries=state.entries.filter(e=>e.id!==b.dataset.delete);save();toast('Entry removed')});
}
function label(e){return e.type==='feed'?'Feed':e.type==='sleep'?'Sleep':e.type==='diaper'?'Diaper':'Note'}
function meta(e){if(e.type==='feed')return `${e.method||'Feed'}${e.method==='Breast'&&e.side?' · '+e.side:''}${e.amount?' · '+e.amount+' '+(e.amountUnit||'oz'):''}${e.duration?' · '+e.duration+' min':''}`;if(e.type==='sleep')return `${e.duration||0} minutes`;if(e.type==='diaper')return (e.kind||'wet').replace(/^./,x=>x.toUpperCase());return 'Remembered moment'}
function fields(type,entry=null){if(type==='feed'){let timed=entry&&entry.duration;return '<label>Method<select id="fieldMethod"><option>Breast</option><option>Bottle</option><option>Formula</option><option>Syringe</option><option>Cup</option></select></label><label id="breastSideField">Side<select id="fieldSide"><option>Left</option><option>Right</option><option>Both</option></select></label><label>Amount (optional)<div class="amount-row"><input id="fieldAmount" type="number" min="0" step="0.5" placeholder="Amount"><select id="fieldAmountUnit" aria-label="Amount unit"><option value="oz">oz</option><option value="ml">ml</option></select></div></label>'+(timed?'<label>Duration (minutes)<input id="fieldDuration" type="number" min="1" placeholder="e.g. 20"></label>':'')+'<button type="button" id="startTimer" class="timer-button">Start feed timer</button>'}return type==='sleep'?'<label>Duration (minutes)<input id="fieldDuration" type="number" min="1" placeholder="e.g. 45"></label><button type="button" id="startTimer" class="timer-button">Start sleep timer</button>':type==='diaper'?'<label>Type<select id="fieldKind"><option value="wet">Wet</option><option value="dirty">Dirty</option><option value="both">Wet + dirty</option></select></label>':'<p class="subtle" style="margin-top:14px">Capture a sweet moment, a question, or anything you want to remember.</p>'}
 function bindFeedMethod(){let method=$('#fieldMethod'),side=$('#breastSideField');if(!method||!side)return;let update=()=>{side.hidden=method.value!=='Breast'};method.onchange=update;update()}
 function openModal(type='feed',entry=null,duplicate=false){ editingEntryId=duplicate?null:entry?.id||null; $('#entryType').value=type; $('#dynamicFields').innerHTML=fields(type,entry); $('#entryTime').value=duplicate?new Date().toTimeString().slice(0,5):entry?.time||new Date().toTimeString().slice(0,5); $('#entryNote').value=entry?.note||''; $('#modalTitle').textContent=entry&&!duplicate?'Edit activity':'Log something'; $('#entryForm button[type="submit"]').textContent=entry&&!duplicate?'Save changes':'Save entry'; if(entry&&type==='feed'){ $('#fieldMethod').value=entry.method||'Breast'; $('#fieldSide').value=entry.side||'Both'; $('#fieldAmount').value=entry.amount||''; $('#fieldAmountUnit').value=entry.amountUnit||'oz'; if($('#fieldDuration'))$('#fieldDuration').value=entry.duration||'' }else if(entry&&type==='sleep')$('#fieldDuration').value=entry.duration||'';else if(entry&&type==='diaper')$('#fieldKind').value=entry.kind||'wet'; bindFeedMethod(); $('#modalBackdrop').hidden=false; $('#modalBackdrop').style.display='grid'; bindTimerButton(); $('#entryType').focus() }
 function closeModal(){ if(voiceRecording&&voiceRecognition)voiceRecognition.stop(); editingEntryId=null; $('#modalBackdrop').hidden=true; $('#modalBackdrop').style.display='none' }
 $('#addEntryButton').onclick=()=>openModal(); document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>openModal(b.dataset.quick)); $('#closeModal').onclick=e=>{e.preventDefault();closeModal()}; $('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()}; document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modalBackdrop').hidden)closeModal()}); $('#entryType').onchange=e=>{$('#dynamicFields').innerHTML=fields(e.target.value);bindFeedMethod();bindTimerButton()};
 setupVoiceNote();
 $('#entryForm').onsubmit=e=>{e.preventDefault();let type=$('#entryType').value,existing=editingEntryId?state.entries.find(entry=>entry.id===editingEntryId):null,x=existing?{...existing}:{id:crypto.randomUUID()};x.date=selectedDate;x.time=$('#entryTime').value;x.type=type;x.note=$('#entryNote').value.trim();if(type==='feed'){x.method=$('#fieldMethod').value;x.amount=$('#fieldAmount').value;x.amountUnit=$('#fieldAmountUnit').value;if(x.method==='Breast')x.side=$('#fieldSide').value;else delete x.side;if($('#fieldDuration'))x.duration=$('#fieldDuration').value}else if(type==='sleep')x.duration=$('#fieldDuration').value;else if(type==='diaper')x.kind=$('#fieldKind').value;if(existing)state.entries=state.entries.map(entry=>entry.id===editingEntryId?x:entry);else state.entries.push(x);save();closeModal();toast(existing?'Activity updated':'Saved to '+(selectedDate===today()?'today':'history'));e.target.reset();$('#modalTitle').textContent='Log something';$('#entryForm button[type="submit"]').textContent='Save entry'};
 $('#clearToday').onclick=()=>{if(confirm('Clear all entries for '+formatDate(selectedDate)+'?')){state.entries=state.entries.filter(e=>e.date!==selectedDate);save();toast('Day cleared')}};
 $('#babyNameButton').onclick=()=>{let n=prompt('What should we call your baby?',state.name);if(n&&n.trim()){state.name=n.trim();save()}};
 const exportData=()=>download('tiny-routines.json',JSON.stringify(state,null,2),'application/json'); const exportCsv=()=>{let rows=[['Date','Time','Type','Details','Note'],...state.entries.slice().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(e=>[e.date,e.time,label(e),meta(e),e.note||''])];download('tiny-routines.csv',rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv')}; $('#exportTop').onclick=exportData; $('#downloadJson').onclick=exportData; $('#downloadCsv').onclick=exportCsv; $('#copyData').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(state,null,2));toast('Data copied to clipboard')}catch{toast('Copy unavailable in this browser')}}; $('#copyHandover').onclick=async()=>{try{await navigator.clipboard.writeText(handoverText());toast('Handover copied')}catch{toast('Copy unavailable in this browser')}}; $('#printReport').onclick=()=>window.print(); $('#nightModeButton').onclick=()=>{state.nightMode=!state.nightMode;save()};
 $('#prevDay').onclick=()=>shiftDate(-1); $('#nextDay').onclick=()=>shiftDate(1); $('#jumpToday').onclick=()=>{selectedDate=today();render()}; $('#restoreData').onclick=()=>$('#restoreInput').click(); $('#restoreInput').onchange=e=>{let file=e.target.files[0];if(!file)return;let reader=new FileReader();reader.onload=()=>{try{let restored=JSON.parse(reader.result);if(!restored||!Array.isArray(restored.entries))throw new Error();state={name:restored.name||'little one',entries:restored.entries};save();toast('Backup restored')}catch{toast('That backup could not be read')}};reader.readAsText(file)};
 $('#mobileHome').onclick=()=>{selectedDate=today();render();window.scrollTo({top:0,behavior:'smooth'})}; $('#mobileHistory').onclick=()=>{selectedDate=new Date(Date.now()-86400000).toISOString().slice(0,10);render();window.scrollTo({top:0,behavior:'smooth'})}; $('#mobileAdd').onclick=()=>openModal(); $('#mobileExport').onclick=exportData;
 $('#accessForm').onsubmit=e=>{e.preventDefault();startApp()};
 $('#accessAnswer').oninput=e=>{let digits=e.target.value.replace(/\D/g,'').slice(0,8);let formatted=digits;if(digits.length>2)formatted=digits.slice(0,2)+' / '+digits.slice(2);if(digits.length>4)formatted=digits.slice(0,2)+' / '+digits.slice(2,4)+' / '+digits.slice(4);e.target.value=formatted};
 supabaseClient=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);if(sessionStorage.getItem('tiny-routines-access')==='yes'){$('#authGate').hidden=true;$('#app').hidden=false;loadSharedState()};document.addEventListener('visibilitychange',()=>{if(!document.hidden&&remoteReady)loadSharedState()});
function download(name,data,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href);toast('Download ready')}
function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
setInterval(()=>{if(state.activeTimer)render()},30000);
